known_ingredients = ["artichaut", "boeuf haché", "champignon", "chèvre",
                     "chorizo", "crème fraîche", "gorgonzola", "jambon",
                     "jambon de pays",
                     "jambon de parme", "lardon", "merguez", "miel", "mozzarella", "œuf",
                     "oignon", "oignon confit", "olive", "poivron",
                     "pomme de terre", "poulet", "reblochon", "roquette", "thon", "tomate",
                     "fromage", "viande hachée", "jambon blanc", "bacon", "basilic frais",
                     "persillade", "épinards", "poireaux", "carotte", "ciboulette", "dés de tomate",
                     "base sauce tomate", "anchois", "tomate fraîche", "câpres", "salade verte", "kebab",
                     "gésiers", "magret", "courgette", "poivron", "origan", "asperge", "camembert",
                     "base crème fraîche", "ananas", "andouille", "rillaud", "salade",
                     "base crème moutardée", "crevette", "sauce kebab", "aneth",
                     "viande kebab", "base crème", "coppa", "fenouil", "cocktail de fruits de mer",
                     "saumon fumé", "parmesan", "sauce marocaine", "sauce barbecue", "raclette",
                     "fromage de chèvre", "poireau", "saint-jacques", "taleggio"]

ingredient_tags = ["légume", "viande",
                   "poisson", "fromage", "calorie", "assaisonnement"]

tag_of_ingredient = {"artichaut": "légume", "boeuf haché": "viande", "champignon": "légume",
                     "chèvre": "fromage", "chorizo": "viande", "crème fraîche": "calorie",
                     "gorgonzola": "fromage", "jambon": "viande",
                     "jambon de pays": "viande",
                     "jambon de parme": "viande", "lardon": "viande", "merguez": "viande", "miel": "calorie",
                     "mozzarella": "fromage", "œuf": "calorie",
                     "oignon": "légume", "oignon confit": "légume", "olive": "légume",
                     "poivron": "légume",
                     "pomme de terre": "calorie", "poulet": "viande", "reblochon": "fromage",
                     "roquette": "légume", "thon": "poisson", "tomate": "légume", "fromage": "calorie",
                     "viande hachée": "viande", "jambon blanc": "viande", "bacon": "viande",
                     "basilic frais": "assaisonnement", "persillade": "assaisonnement", "épinards": "légume",
                     "poireaux": "légume", "carotte": "légume", "ciboulette": "assaisonnement",
                     "dés de tomate": "légume", "base sauce tomate": "légume", "anchois": "poisson",
                     "tomate fraîche": "légume", "salade verte": "légume", "kebab": "viande", "câpres": "assaisonnement",
                     "gésiers": "légume", "magret": "légume", "courgette": "légume", "poivron": "légume",
                     "origan": "assaisonnement", "asperge": "légume", "camembert": "fromage",
                     "base crème fraîche": "assaisonnement", "ananas": "assaisonnement", "salade": "légume",
                     "rillaud": "viande", "andouille": "viande", "base crème moutardée": "assaisonnement",
                     "crevette": "poisson", "sauce kebab": "assaisonnement", "aneth": "assaisonnement",
                     "viande kebab": "viande", "coppa": "viande", "base crème": "assaisonnement",
                     "fenouil": "légume", "cocktail de fruits de mer": "poisson", "saumon fumé": "poisson",
                     "parmesan": "fromage", "sauce marocaine": "assaisonnement", "sauce barbecue": "assaisonnement",
                     "raclette": "calorie", "poireau": "légume", "saint-jacques": "poisson",
                     "fromage de chèvre": "fromage", "taleggio": "fromage"
                     }
